### ISSUE TITLE
Hosted Trial gives error: 500 Internal Server Error.

### ISSUE THREAD

**Issue by frakman1** [AppMini/todoMini#19]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/5826484/171002676-7ed7289d-393f-422a-8942-bf1738572b27.png">

Clicking on the "Try it free" button for "Get the hosted version free for a month so you can try it out." results in this error:

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/5826484/171002392-f3d9f90f-f7d9-4623-9b85-c08ad99a0560.png">

**Comment by chr15m** [comment]
Have moved the demo to https://todomini.app
