### ISSUE TITLE
[EVO] Show ticked tasks

### ISSUE THREAD

**Issue by ThmsP** [AppMini/todoMini#2]
Hello, this is not really an issue more an ask for evolution. 
Do you think it would be possible do show the ticked tasks ? There are still presents in the data file so ...
Thanks !

**Comment by chr15m** [comment]
Hi! On my version a tick mark appears in the circle next to the items as you tick them off - does this not happen for you? 

Can you send me an example data file and/or screenshot and describe what you expect versus what actually happens?

**Comment by ThmsP** [comment]
Sorry, I think I wasn't well awake ... I made a new test and the tick marck appears in the circles and the item stay visible. 
Anyway thanks for your answer ! And your app seems great ! Will do more testing !

**Comment by chr15m** [comment]
@ThmsP there is a bug which may be causing what you saw which I have filed on #3.
