### ISSUE TITLE
Security issue: ability to read files from demo server

### ISSUE THREAD

**Issue by benharvie** [AppMini/todoMini#21]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@thelabda) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by chr15m** [comment]
Hello @benharvie and @thelabda, please feel free to report the issue here.

**Comment by thelabda** [comment]
Dear Chris,

Thanks for your response!
You can find all the details about the issue, I found in the AppMini
application:

https://huntr.dev/bounties/e648d8ed-2224-4684-bd13-3eb2ea6429f0/

This report is only accessible for the repository's maintainer and myself.
If you aren't happy to sign-up, let me know, and I can arrange for the
platform team to send you a magic link to give you privileged access.

Let me know if you have any questions, and I am more than happy to help.

Best wishes,
Labda

Chris McCormick ***@***.***> ezt írta (időpont: 2023. jún.
29., Cs, 2:50):

**Comment by chr15m** [comment]
Cool, yes, send through the magic link thank you.

**Comment by thelabda** [comment]
Dear Chris,

Can you please drop me an e-mail address, where we can generate the magic
link?

Thanks,

Labda

Chris McCormick ***@***.***> ezt írta (időpont: 2023. jún.
29., Cs, 8:57):

**Comment by chr15m** [comment]
@thelabda my work domain is mccormickit.com and you can append my first name ("chris") and then an at symbol to that. Thanks!

**Comment by chr15m** [comment]
Thanks for the email about the security issue.

According to your email the following files are publicly readable:

* https://appmini.github.io/todoMini/example.htaccess
* https://appmini.github.io/todoMini/server.php

Given these files are available anyway as part of the public source code I fail to see how this consitutes a vulnerability. Let me know if I am missing something here.
