### ISSUE TITLE
Is this Project still being actively maintained (Project dead)?

### ISSUE THREAD

**Issue by Rabenherz112** [AppMini/todoMini#22]
Hey there,

just wanted to know if the project is still being actively maintained or if it has been abandoned.

**Comment by chr15m** [comment]
Neither. It is not maintained because it does not need maintenance. It is not abandoned. I use it every day with my wife to do our shopping for example.

I need to fix up the website which I will do.

**Comment by nodiscc** [comment]
> it does not need maintenance.

- It could need some maintenance to stay compatible with supported PHP versions. Currently PHP versions older than 8.0 have reached [end-of-life](https://www.php.net/supported-versions.php). Does todoMini work with PHP 8?
- could you check whether the supposed security vulnerability mentioned at https://github.com/AppMini/todoMini/issues/21 effectively exists/is applicable?

Ref. https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3928

**Comment by chr15m** [comment]
@nodiscc Ok cool, maybe best to mark it as unmaintained for now until I or somebody else gets some time to look into these issues. Thanks.

**Comment by chr15m** [comment]
@nodiscc I have tested on PHP 8, fixed a bunch of bugs, created a new build, and the vulnerability you mentioned has been investigated and deemed not relevant. Also I recently merged a couple of PRs. I believe this app can be once again considered "maintained".
