### ISSUE TITLE
The word "dingus" in the first line of server.php file in v0.5 zip

### ISSUE THREAD

**Issue by mduret** [AppMini/todoMini#24]
Hello,

I use this software since many years. Thank you for this.

Recently, I upgrade it to the 0.5 version and I found a little snag.

if I extract the two first lines of `server.php`  file in version 0.5 zip archive :

```
curl -sL https://github.com/AppMini/todoMini/releases/download/0.5/todomini.zip --output /tmp/todomini.zip && \
unzip -p /tmp/todomini.zip todomini/server.php | head -n 2 && \
rm /tmp/todomini.zip
```

I see that there is the word `dingus` at the first line :

```
dingus
<?php
```

It is not very important, but it can be usefull to remove it for easier use.

Thanks and have a good day !

**Comment by chr15m** [comment]
Wow. :facepalm:

Will fix this. Thank you for letting me know. :pray:

**Comment by chr15m** [comment]
Published a new release and this should be fixed now, thanks!
